export const environment = {
  production: true,
  CURRENT_LANGUAGE: 'current_language',
  TOKEN: 'token',
  LOGGED_IN: 'logged_in',
  LOGOUT: 'logout',
  COMPANY: 'company',
  REGION: 'region',
  REGION_DATA: 'region_data',
  DOMESTIC_CURRENCY: 'domesticCurrency',
  TIME_ZONE: 'timezone',
  startDate: '01/Jan/1900 12:00:00 PM',
  endDate: '06/Jun/2079 12:59:59 PM',
  JOB_DATA: 'job_data',
  USER_INFO: 'user_info',
  TIMESTAMP_APP: 'timestamp',
  API_URL: 'http://localhost:8080/api/',
  CONTENT: 'application/json',
  VERSION: '1.0.0.0',
};